# Generated by Django 4.0.1 on 2022-01-25 02:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('littlesealbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='littlesealstatus',
            name='last_clean_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 25, 2, 28, 15, 546640)),
        ),
        migrations.AddField(
            model_name='littlesealstatus',
            name='last_drink_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 25, 2, 28, 15, 546606)),
        ),
        migrations.AddField(
            model_name='littlesealstatus',
            name='last_fed_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 25, 2, 28, 15, 546567)),
        ),
        migrations.AddField(
            model_name='littlesealstatus',
            name='last_happy_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 25, 2, 28, 15, 546678)),
        ),
        migrations.AddField(
            model_name='littlesealstatus',
            name='last_play_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 25, 2, 28, 15, 546708)),
        ),
        migrations.AddField(
            model_name='littlesealstatus',
            name='last_sleep_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 25, 2, 28, 15, 546736)),
        ),
        migrations.AlterField(
            model_name='littlesealstatus',
            name='desier',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='littlesealstatus',
            name='sentense',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
