# Generated by Django 4.0.1 on 2022-01-25 02:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('littlesealbot', '0002_littlesealstatus_last_clean_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='littlesealstatus',
            name='last_clean_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 25, 2, 30, 52, 510869, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='littlesealstatus',
            name='last_drink_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 25, 2, 30, 52, 510804, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='littlesealstatus',
            name='last_fed_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 25, 2, 30, 52, 510720, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='littlesealstatus',
            name='last_happy_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 25, 2, 30, 52, 510978, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='littlesealstatus',
            name='last_play_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 25, 2, 30, 52, 511020, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='littlesealstatus',
            name='last_sleep_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 25, 2, 30, 52, 511051, tzinfo=utc)),
        ),
    ]
