# Generated by Django 4.0.1 on 2022-01-25 01:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeddyStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hunger', models.PositiveIntegerField(default=0)),
                ('thirst', models.PositiveIntegerField(default=0)),
                ('cleanliness', models.PositiveIntegerField(default=100)),
                ('happiness', models.PositiveIntegerField(default=100)),
                ('excited', models.PositiveIntegerField(default=50)),
                ('sleepiness', models.PositiveIntegerField(default=0)),
                ('desier', models.CharField(max_length=32)),
                ('sentense', models.CharField(max_length=128)),
            ],
        ),
    ]
