# Generated by Django 4.0.1 on 2022-01-25 02:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('teddybot', '0002_teddystatus_last_clean_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teddystatus',
            name='last_clean_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 25, 2, 30, 52, 508375, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='teddystatus',
            name='last_drink_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 25, 2, 30, 52, 508306, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='teddystatus',
            name='last_fed_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 25, 2, 30, 52, 507881, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='teddystatus',
            name='last_happy_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 25, 2, 30, 52, 508435, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='teddystatus',
            name='last_play_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 25, 2, 30, 52, 508496, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='teddystatus',
            name='last_sleep_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 25, 2, 30, 52, 508553, tzinfo=utc)),
        ),
    ]
