# Generated by Django 4.0.1 on 2022-01-25 02:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('teddybot', '0003_alter_teddystatus_last_clean_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teddystatus',
            name='last_clean_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='teddystatus',
            name='last_drink_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='teddystatus',
            name='last_fed_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='teddystatus',
            name='last_happy_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='teddystatus',
            name='last_play_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='teddystatus',
            name='last_sleep_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
